version: "3.1"

services:
  datadog-agent:
    container_name: datadog-agent
    environment:
      - DD_API_KEY=$DD_API_KEY
      - DD_HOSTNAME=datadog-data-privacy-logs
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_ENABLED=true
      - DD_SITE=$DD_SITE
      - DD_TAGS=env:dev
      # (1) TODO: Uncomment the following line to begin excluding Datadog Agent logs.
      # - DD_CONTAINER_EXCLUDE_LOGS=image:datadog/agent
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
  cardpayment-masked:
    container_name: cardpayment-masked
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - datadog-agent
    # (2) TODO: Uncomment the labels section to begin masking credit card numbers present in logs.
    # labels:
    #   com.datadoghq.ad.logs: >-
    #     [{
    #         "source": "python",
    #         "service": "cardpayment-masked",
    #         "log_processing_rules": [
    #             {
    #                 "type": "mask_sequences",
    #                 "name": "mask_credit_cards",
    #                 "replace_placeholder": "[CREDIT CARD REDACTED]",
    #                 "pattern": "(?:4[0-9]{12}(?:[0-9]{3})?|[25][1-7][0-9]{14}|6(?:011|5[0-9][0-9])[0-9]{12}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|(?:2131|1800|35\\d{3})\\d{11})"
    #             },
    #             {
    #                 "type": "mask_sequences",
    #                 "name": " social_security_number_basic",
    #                 "replace_placeholder": "[SSN REDACTED]",
    #                 "pattern": "(?:\\d{3}-?\\d{2}-?\\d{4})"
    #             }
    #         ]
    #     }]
  cardpayment-raw:
    container_name: cardpayment-raw
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - datadog-agent
    # (3) TODO: Uncomment in the labels section to update the serive tag applied to this container's logs.
    # labels:
    #   com.datadoghq.ad.logs: >-
    #     [
    #         {
    #             "source": "python",
    #             "service": "cardpayment-raw"
    #         }
    #     ]
